from .interface import EstimatorInterface
from .linr import LinearRegression
from .lr import LogisticRegression
from .dt import DecisionTree
from .rf import RandomForest
from .svm import SVM
from .nn import NN
from .cnn import CNN
from .pca import PCA
from .tsne import TSNE